### ISSUE TITLE
error on calling tag_file.py

### ISSUE THREAD

**Issue by vanatteveldt** [rubenIzquierdo/opinion_miner_deluxePP#2]
```
$ ~/newsreader_pipe_nl/newsreader-env/bin/python tag_file.py -f ../../tools/opinion_miner_models/models/models_news_nl/ -polarity < /tmp/test.naf 
Traceback (most recent call last):
  File "tag_file.py", line 175, in <module>
    feature_file = expression_feature_extractor(kaf_naf_obj,'tag', model_folder, log=args.log)
  File "/data/wva/newsreader_pipe_nl/modules/opinion_miner_deluxePP/extract_features_expression.py", line 489, in main
    from mpqa_lexicon import MPQA_subjectivity_lexicon
ImportError: No module named mpqa_lexicon
```

Did I forget to install something?

**Comment by rubenIzquierdo** [comment]
This is not necessary neither use for other languages than English, but I included the module now anyway to avoid the exception

**Comment by vanatteveldt** [comment]
it works, thanks!
